services:
  - type: web
    name: xx-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: PUBMED_EMAIL
        sync: false
      - key: PUBMED_API_KEY
        sync: false
      - key: OPENAI_API_KEY
        sync: false

  - type: static-site
    name: xx-frontend
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: frontend/dist
    envVars:
      - key: VITE_API_URL
        value: https://xx-backend.onrender.com 